- uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ccodesmithh
          template: classic
          # Kita batasi hanya informasi penting agar tidak terlalu panjang
          base: header, community
          config_timezone: Asia/Jakarta
          
          # Pengaturan Layout agar lebih ramping
          config_padding: 0, 8%
          config_order: base.header, base.community, plugin_languages, plugin_lines

          # Plugin Bahasa dibuat compact (dua kolom)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          
          # Plugin Garis kode dibuat kecil saja
          plugin_lines: yes
