name: Metrics
on:
  # Update otomatis setiap 12 jam
  schedule: [{cron: "0 */12 * * *"}]
  # Jalankan manual jika ingin update instan
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Konfigurasi tampilan
          user: ccodesmithh
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Jakarta
          
          # Tambahan plugin keren
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes
