name: Metrics
on:
  # Update otomatis setiap 12 jam
  schedule: [{cron: "0 */12 * * *"}]
  # Memungkinkan dijalankan manual dari tab Actions
  workflow_dispatch:
  # Update tiap ada push ke branch main atau master
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Pastikan kamu sudah buat secret METRICS_TOKEN di Settings
          token: ${{ secrets.METRICS_TOKEN }}

          # Konfigurasi User
          user: ccodesmithh
          template: classic
          base: header, community
          config_timezone: Asia/Jakarta
          
          # Pengaturan agar lebih ramping (Proportional)
          config_padding: 0, 8%
          config_order: base.header, base.community, plugin_languages, plugin_lines

          # Plugin Bahasa (Dibuat ringkas)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          
          # Plugin Baris Kode
          plugin_lines: yes
